# Generated by Django 5.0 on 2023-12-21 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='selected_symbol',
            field=models.CharField(choices=[('apple.png', 'Apple'), ('bomb.png', 'Bomb')], default='apple.png', max_length=100),
        ),
    ]
