# Generated by Django 5.0 on 2023-12-24 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_selected_symbol'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='selected_symbol',
        ),
        migrations.AddField(
            model_name='profile',
            name='symbol',
            field=models.ImageField(default='bomb.png', upload_to='symbols'),
        ),
    ]
