# Generated by Django 5.0 on 2023-12-12 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('morpion', '0005_game_alignement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='content',
        ),
    ]
