# Generated by Django 5.0 on 2023-12-12 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('morpion', '0006_remove_game_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='gameover',
            field=models.BooleanField(default=False),
        ),
    ]
