# Generated by Django 5.0 on 2023-12-19 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('morpion', '0008_game_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='access_code',
            field=models.CharField(default='EVANQUVW', max_length=8, unique=True),
        ),
    ]
