# Generated by Django 5.0 on 2023-12-21 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('morpion', '0012_game_current_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='board',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
