# Generated by Django 5.0 on 2024-01-02 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('morpion', '0017_game_is_ff_game_loser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='ff_message',
        ),
        migrations.AddField(
            model_name='game',
            name='exist_winner',
            field=models.BooleanField(default=False),
        ),
    ]
